import Vue from 'vue'


import { Link,Row,Col, Button, Form, FormItem, Input, Switch, Table, TableColumn, Pagination, RadioGroup, Radio,Checkbox,CheckboxGroup,Upload,DatePicker,Dialog,Progress,Loading,Card,Image,Tooltip} from 'element-ui'
Vue.use(Button)
    .use(Form)
    .use(FormItem)
    .use(Input)
    .use(Switch)
    .use(Table)
    .use(TableColumn)
    .use(Pagination)
    .use(RadioGroup)
    .use(Radio)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Upload)
    .use(DatePicker)
    .use(Row)
    .use(Col)
    .use(Link)
    .use(Dialog)
    .use(Progress)
    .use(Loading)
    .use(Card)
    .use(Image)
    .use(Tooltip)